# Generated by Django 5.0.6 on 2024-07-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
